services:
  app:
    build: .
    container_name: messager-service
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: message-service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - "/c/Users/Josiane Ap Nogueira/Documents/dev/messager-service/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
